SELECT *
FROM MILAN_WEATHER_HOURLY
ORDER BY DATETIME
LIMIT 5;


SELECT
    COUNT(*) AS DAYS,
    MIN(DAILY_RAIN) AS MIN_RAIN,
    MAX(DAILY_RAIN) AS MAX_RAIN,
    AVG(DAILY_RAIN) AS AVG_RAIN
FROM (
    SELECT
        CAST(DATETIME AS DATE) AS OBS_DATE,
        SUM(RAIN) AS DAILY_RAIN
    FROM MILAN_WEATHER_HOURLY
    GROUP BY CAST(DATETIME AS DATE)
);
